botToken:   "balblabla"

# Discord messages for in game events
events:
  onStart:
    enabled: true
    channel: "id..."
    
  onStop:
    enabled: true
    channel: "id..."

  onJoin:
    enabled: true
    channel: "id..."

  onLeave:
    enabled: true
    channel: "id..."

  onMessage:
    enabled: true
    forwardCommands: false
    channels:
      server1: "id..."
      server2: "id..."

# Whistlisting via discord
whitelist:
  enabled: true
  onAccept:
    enabled: true
    channel: "id..."
  onDeny:
    enabled: true
    channel: "id..."
  request:
    enabled: true
    channel: "id..."
    checkRoles: false
    allowedRoles: []
  voting:
    # If disabled, a request will imply immediate whitelist
    enabled: true
    channel: "id.."
    checkRoles: false
    allowedRoles: []
    acceptVotes: "50%"
    denyVotes: "1"

# Banning via discord
banning:
  enabled: true
  request:
    enabled: true
    channel: "id..."
    checkRoles: false
    allowedRoles: []
  voting:
    enabled: true
    channel: "id..."
    checkRoles: false
    allowedRoles: []
    acceptVotes: "50%"
    denyVotes: "1"