# !This file must be setup before using this plugin!
# Once a feature is enabled, disabling it again may result in undefined behavior
# If you really want to disable a feature, but this wrecks your whitelist/install, you should delete the data.yml file

botToken:   "Insert your token here, see the README.md on how to get a token"
# Guild ID is needed for adding commands
guildId:    "Insert your guild id here (the ID of your discord server)"

# Discord messages for in game events
events:
  onStart:
    enabled: false
    channel: "id..."
    
  onStop:
    enabled: false
    channel: "id..."

  onJoin:
    enabled: false
    channel: "id..."

  onLeave:
    enabled: false
    channel: "id..."

  onMessage:
    enabled: false
    minecraftToDiscord: true
    discordToMinecraft: true

    # Uncomment the one that applies to your server type:

    # For fabric:
    # channels:
    #   fabric: "id..."

    # For velocity
    # (The server names are the ones specified in the velocity.toml file you configured)
    # Do not share discord channels if you have discordToMinecraft enabled
    # channels:
    #   server1: "id..."
    #   server2: "id..."


# If enabled, will use the UUID registered at mojang for verification
# !Will force the server into online mode!
# You currently cannot change this setting after you have someone whitelisted, so choose carefully
# If you really want to change this, delete the data.yml file (this will remove all whitelisted players, they will need to be whitelisted again)
useUUID: true
# If enabled only one minecraft account is allowed per discord user
# You currently cannot change this setting after you have someone whitelisted, so choose carefully
# If you really want to change this, delete the data.yml file (this will remove all whitelisted players, they will need to be whitelisted again)
connectAccounts: true

# Whitelisting via discord
whitelist:
  enabled: false

  # Should this plugin give someone that is whitelisted a special role
  giveRoleOnWhitelist: false
  # The role to give a player when he is whitelisted (only if giveRoleOnWhitelist=true)
  # Enable developer options to get the role ID easily from the discord-server settings:
  whitelistedRoleID: ""

  onAccept:
    enabled: true
    channel: "id..."
  onDeny:
    enabled: true
    channel: "id..."
  request:
    enabled: true
    channel: "id..."
    checkRoles: false
    allowedRoles: []
  voting:
    # If disabled, a request will imply immediate whitelist
    enabled: true
    channel: "id.."
    checkRoles: false
    allowedRoles: []
    acceptVotes: "50%"
    denyVotes: "1"

# Banning via discord
banning:
  enabled: false
  request:
    enabled: true
    channel: "id..."
    checkRoles: false
    allowedRoles: []
  voting:
    # If disabled, a request will imply an immediate ban
    enabled: true
    channel: "id..."
    checkRoles: false
    allowedRoles: []
    acceptVotes: "50%"
    denyVotes: "1"

maintenance:
  # Disables events and rejects everyone not on the crew list
  enabled: false
  # Enable maintenance mode from the config:
  inMaintenance: false
  # Players allowed to join during maintenance
  # Use UUID's if useUUID=true, else use player names
  # This does not override the whitelist and banning features, you still need to be whitelisted to enter
  crew: ["player1", "player2"]
  # Command to enable maintenance mode via discord
  command:
    enabled: false
    checkChannel: true
    allowedChannels: ["id..."]
    checkRoles: false
    allowedRoles: []
  # On start messages
  onStart:
    enabled: false
    channel: "id..."
  # On end message
  onStop:
    enabled: false
    channel: "id..."